name: identix
description: Blockchain-Based Time-Bound Identity Verification App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^1.1.2
  
  # QR Generation & Scanning
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.5
  
  # Cryptography
  crypto: ^3.0.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # URL Launcher
  url_launcher: ^6.2.2

  # Date formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
